pnp/sp-dev-solutions

- solutions/ColumnFormatter/npm-shrinkwrap.json
- solutions/ColumnFormatter/src/webparts/columnFormatter/components/ColumnFormatter.module.scss
- solutions/ColumnFormatter/src/webparts/columnFormatter/loc/fr-fr.js
- solutions/ColumnFormatter/src/webparts/columnFormatter/loc/old_fr-fr.js
Hi,
Add French translation with little modifications of CSS for too long translations.
Thanks,
Richard
> Add french translations

- solutions/ColumnFormatter/src/webparts/columnFormatter/loc/de-de.js
Added German translation files to Column Formatter.
| Related issues?  | #6 
Added translation file for German to the project. No feature update, only language.
> Added German Translation to Column Formatter.

- solutions/SiteDesignsStudio/schemas/schema.20180602.json
| Bug fix?        |  Yes
| New feature?    | No
| New sample?      | No
| Related issues?  | fixes #24 
Fixed duplicate field name in the Schema for CreateSiteContentType
> Fixed Duplicate Field Name

- solutions/LinksAndHandlebarsTemplate/src/webparts/boxButtonWebPart/BoxButtonWebPartWebPart.ts
- solutions/LinksAndHandlebarsTemplate/src/webparts/featuredContentWebPart/FeaturedContentWebPartWebPart.ts
Fixed a bug in the boxbutton and featuredcontent webparts under linkandhandlebarstemplate involving length being undefined.
| Bug fix?        |  yes
| New sample?      | no 
| Related issues?  | none
Please describe the changes in this PR. Sample description or details around bugs which are being fixed.
There was a bug in both the boxbutton and featuredcontent webparts in the linksandhandelbars template solution where it tries to loop through an array and errors out because the syntax is wrong. I just fixed the syntax.
> Fixed a bug in the boxbutton and featuredcontent webparts

- solutions/ModernSearch/react-search-refiners-renderer/package.json
- solutions/ModernSearch/react-search-refiners/spfx/package.json
Hi,
adding resolution in package.json for react types for compatibility with Yarn.
Thanks for this great webpart ;)
> [fix] - add resolution for react types for compatibility with Yarn

- solutions/ModernSearch/react-search-refiners/README.md
I tested all the [out of the box search query variables](https://docs.microsoft.com/en-us/sharepoint/technical-reference/query-variables) with the web part, and updated the README with the list of those that actually work.
> [ModernSearch] Supported query variables

- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchBox/SearchBoxWebPart.ts
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchResults/SearchResultsWebPart.ts
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchResults/components/SearchResultsContainer/ISearchResultsContainerProps.ts
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchResults/components/SearchResultsContainer/SearchResultsContainer.tsx
| Bug fix?        | yes https://github.com/SharePoint/sp-dev-solutions/issues/93
Fixed a bug when the URL fragment contains multiple keywords.
> [ModernSearch] Fixed URL fragment encoding for search results WP

- solutions/ModernSearch/react-search-refiners/spfx/package-lock.json
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchResults/components/SearchResultsContainer/SearchResultsContainer.tsx
| Bug fix?        | yes #95 #96
Revert changes made to new SearchResultsContainer regarding new props handling.
>  [ModernSearch] Revert changes made to new SearchResultsContainer regarding new props handling.

- README.md
- solutions/ModernSearch/react-search-refiners/package-lock.json
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/controls/TextDialog/TextDialog.tsx
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchPagination/SearchPaginationWebPart.ts
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchPagination/components/SearchPaginationContainer/ISearchPaginationContainerProps.ts
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchPagination/components/SearchPaginationContainer/SearchPaginationContainer.tsx
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchPagination/loc/en-us.js
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchPagination/loc/fr-fr.js
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchPagination/loc/mystrings.d.ts
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchRefiners/components/Layouts/LinkPanel/LinkPanel.tsx
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchRefiners/components/Layouts/Vertical/Vertical.tsx
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchRefiners/components/SearchRefinersContainer/SearchRefinersContainer.tsx
| Related issues?  | mentioned in #72  
* Improved pagination webpart when in edit mode and no results are available > show a message instead of empty
* Optimized some Office UI Fabric imports
* Added ModernSearch in the main README solution overview
* Added a missing semi colon
* Removed a stray package-lock.json file
@wobba @FranckyC
> [ModernSearch] Pagination edit mode improvement

- solutions/README-template.md
A few minor changes to README-template.md based on markdown validation.
> Markdown updates

- solutions/ModernSearch/react-search-refiners/spfx/src/models/IRefinerConfiguration.ts
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchRefiners/SearchRefinersWebPart.ts
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchRefiners/components/Layouts/LinkPanel/LinkPanel.tsx
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchRefiners/components/Layouts/Vertical/Vertical.tsx
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchRefiners/loc/en-us.js
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchRefiners/loc/fr-fr.js
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchRefiners/loc/mystrings.d.ts
| Bug fix?        | no 
| New sample?      | no 
| Related issues?  | fixes #120 
Needed something similar to the feature asked in #120 for my project.
It was implemented it as a property in the RefinerConfiguration. It is not a global toggle applied to all refiners but unless you have a lot of refiners I doubt it would be much of an issue.
Thanks for your contribution! Sharing is caring.
> Refiners expanded by default

- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchBox/components/SearchBoxContainer/ISearchBoxContainerState.ts
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchBox/components/SearchBoxContainer/SearchBoxContainer.tsx
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchBox/components/SearchBoxWebPart.module.scss
| Related issues?  | fixes #119, mentioned in #72 
Added clear button that will reset the search box to its initial state (works with escape key too).
> [ModernSearch] Add "clear" button

- solutions/MultilingualPages/README.md
| Related issues?  | N/A
Add link to PnP YouTube video demoing solution.
> Add Video demo

- solutions/ModernSearch/react-search-refiners/README.md
| Bug fix?        | no - yes?
| New feature?    | no - yes?
| New sample?      | no - yes?
| Related issues?  | fixes #X, partially #Y, mentioned in #Z
Please describe the changes in this PR. Sample description or details around bugs which are being fixed.
*You can delete this section when you are submitting the pull request.* 
* *Please update this PR information accordingly. We'll use this as part of our release notes in monthly communications.*
* *Please target your PR to 'dev' branch.*
Thanks for your contribution! Sharing is caring.
> Updated version number

- solutions/ModernSearch/react-search-refiners/README.md
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchBox/loc/en-us.js
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchResults/loc/en-us.js
| Bug fix?        |  yes
| Related issues?  | partially #84
Updated readme.md and localization files that contained several typo's. 
Did not create a issue for it due to the nature of the fix.
> [ModernSearch] language fixes for typo's

- solutions/MultilingualPages/README.md
| New sample?      | yes (?)
| Related issues?  | mentions #175 and #207
Important information about setting up this solution.
I did multiple builds/installations now and problems tend to be:
* the wrong node.js version is being installed since the official SPFx documentation says to install version 10 - this is not supported
* tenant admins need to be informed beforehand - so let's highlight this requirement since it always comes as a surprise
* setup as non-English user fails - let's be honest about this
@juliemturner
> Add important information for setup

- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchNavigation/ISearchNavigationWebPartProps.ts
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchNavigation/SearchNavigationWebPart.manifest.json
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchNavigation/SearchNavigationWebPart.ts
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchNavigation/components/SearchNavigationContainer/ISearchNavigationContainerProps.ts
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchNavigation/components/SearchNavigationContainer/SearchNavigationContainer.tsx
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchNavigation/loc/en-us.js
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchNavigation/loc/es-es.js
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchNavigation/loc/fr-fr.js
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchNavigation/loc/mystrings.d.ts
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchNavigation/loc/nl-nl.js
Added the ability to disable sending an existing query to the new page when navigating using Search navigation web part
> [ModernSearch] Optional query passing for Search navigation web part

- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchBox/SearchBoxWebPart.manifest.json
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchNavigation/SearchNavigationWebPart.manifest.json
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchPagination/SearchPaginationWebPart.manifest.json
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchRefiners/SearchRefinersWebPart.manifest.json
- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchVerticals/SearchVerticalsWebPart.manifest.json
Sometimes (probably depending on load order) some web parts don't style correctly, adding the loading of the legacy css property on all web parts fixes that.
> Fix unstyled content

- solutions/ModernSearch/react-search-refiners/spfx/src/services/TemplateService/BaseTemplateService.tsx
Fix loading the icons from CDN
> [ModernSearch] Fix load icons

- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchRefiners/components/Templates/FixedDateRange/FixedDateRangeTemplate.tsx
Removed another hardcoded string
> [ModernSearch] Localization fix

- solutions/ModernSearch/react-search-refiners-renderer/.yo-rc.json
- solutions/ModernSearch/react-search-refiners-renderer/package-lock.json
- solutions/ModernSearch/react-search-refiners-renderer/package.json
Upgrade renderers project to SPFx 1.9.1
> [ModernSearch] Renderers upgrade 191

- solutions/ModernSearch/react-search-refiners/spfx/src/webparts/searchBox/components/SearchBoxContainer/SearchBoxContainer.tsx
Fix clearing of the searchbox when searchtext is loaded from URL. Previously, the passed in searchtext became the default searchtext which couldn't be cleared. Now, this passed in searchtext can be cleared.
> [ModernSearch] Improve searchbox clearing

- solutions/ChangeRequests/README.md
- solutions/ChangeRequests/config/package-solution.json
- solutions/ChangeRequests/package-lock.json
- solutions/ChangeRequests/package.json
- solutions/ChangeRequests/src/libraries/provisioning/ProvisionManager.ts
- solutions/ChangeRequests/src/libraries/solutions/SharePointUtility.ts
- solutions/ChangeRequests/src/pnp-preset.ts
- solutions/ChangeRequests/src/webparts/changeRequestManagementWebPart/dataProviders/CRManagementDataProvider.ts
- solutions/ChangeRequests/src/webparts/myChangeRequestsWebPart/dataProviders/MyCRDataProvider.ts
Updates ChangeRequests to use PnPjs
> Updates ChangeRequests to use PnPjs

- solutions/LeadsLOBSolution/README.md
- solutions/LeadsLOBSolution/webpart/config/package-solution.json
- solutions/LeadsLOBSolution/webpart/package-lock.json
- solutions/LeadsLOBSolution/webpart/package.json
- solutions/LeadsLOBSolution/webpart/src/webparts/leads/LeadsWebPart.ts
- solutions/LeadsLOBSolution/webpart/src/webparts/leads/components/Leads/ILeadsProps.ts
- solutions/LeadsLOBSolution/webpart/src/webparts/leads/components/Leads/ILeadsState.ts
- solutions/LeadsLOBSolution/webpart/src/webparts/leads/components/Leads/Leads.tsx
Adds support for creating Planner reminder for a lead
> Adds support for creating Planner reminder for a lead

- solutions/ContactManagement/config/package-solution.json
- solutions/ContactManagement/package-lock.json
- solutions/ContactManagement/package.json
- solutions/ContactManagement/src/biz/ProvisionManager.ts
- solutions/ContactManagement/src/data/CrmManager.ts
- solutions/ContactManagement/src/dataProviders/BaseCrmDataProvider.ts
- solutions/ContactManagement/src/dataProviders/SharePointCrmDataProvider.ts
- solutions/ContactManagement/src/libraries/solutions/SharePointUtility.ts
- solutions/ContactManagement/src/pnp-preset.ts
- solutions/ContactManagement/src/webparts/crm/CrmWebPart.ts
Changes ContactManagement to use PnPjs
> Changes ContactManagement to use PnPjs

- solutions/LeadsLOBSolution/README.md
- solutions/LeadsLOBSolution/webpart/config/package-solution.json
- solutions/LeadsLOBSolution/webpart/package-lock.json
- solutions/LeadsLOBSolution/webpart/package.json
- solutions/LeadsLOBSolution/webpart/src/webparts/leads/LeadsWebPart.ts
- solutions/LeadsLOBSolution/webpart/src/webparts/leads/components/Leads/ILeadsProps.ts
- solutions/LeadsLOBSolution/webpart/src/webparts/leads/components/Leads/Leads.tsx
Switches to To Do for creating personal reminders
> Switches to To Do for creating personal reminders

- solutions/InventoryCheckOut/README.md
- solutions/InventoryCheckOut/config/package-solution.json
- solutions/InventoryCheckOut/package-lock.json
- solutions/InventoryCheckOut/package.json
- solutions/InventoryCheckOut/src/libraries/solutions/SharePointUtility.ts
- solutions/InventoryCheckOut/src/pnp-preset.ts
- solutions/InventoryCheckOut/src/webparts/inventoryCheckOutWebPart/InventoryCheckOutWebPartWebPart.ts
- solutions/InventoryCheckOut/src/webparts/inventoryCheckOutWebPart/components/Container/CheckOutContainer.tsx
- solutions/InventoryCheckOut/src/webparts/inventoryCheckOutWebPart/dataProviders/InventoryCheckOutDataProvider.ts
- solutions/InventoryCheckOut/src/webparts/inventoryCheckOutWebPart/provisioning/ProvisionManager.ts
Updates InventoryCheckOut to use PnPjs
> Updates InventoryCheckOut to use PnPjs

- solutions/TimeAway/README.md
- solutions/TimeAway/package-lock.json
- solutions/TimeAway/package.json
- solutions/TimeAway/src/libraries/components/Container/MyTimeAwayContainer.tsx
- solutions/TimeAway/src/libraries/dataProviders/SharePointDataProvider.ts
- solutions/TimeAway/src/libraries/provisioning/TimeAwayManager.ts
- solutions/TimeAway/src/libraries/solutions/SharePointUtility.ts
- solutions/TimeAway/src/pnp-preset.ts
- solutions/TimeAway/src/webparts/myTimeAway/MyTimeAwayWebPart.ts
- solutions/TimeAway/src/webparts/timeAwaySummary/TimeAwaySummaryWebPart.ts
- solutions/TimeAway/src/webparts/timeAwaySummary/components/Container/TimeAwaySummaryContainer.tsx
- solutions/TimeAway/src/webparts/timeAwaySummary/dataProviders/ITimeAwaySummaryDataProvider.ts
- solutions/TimeAway/src/webparts/timeAwaySummary/dataProviders/TimeAwaySummaryDataProvider.ts
> Changes TimeAway to use PnPjs

- solutions/LeadsLOBSolution/README.md
- solutions/LeadsLOBSolution/webpart/config/package-solution.json
- solutions/LeadsLOBSolution/webpart/package.json
- solutions/LeadsLOBSolution/webpart/src/LeadsSettings.ts
- solutions/LeadsLOBSolution/webpart/src/webparts/leads/LeadsWebPart.manifest.json
- solutions/LeadsLOBSolution/webpart/src/webparts/leads/LeadsWebPart.ts
- solutions/LeadsLOBSolution/webpart/src/webparts/leadsSettings/LeadsSettingsWebPart.ts
- solutions/LeadsLOBSolution/webpart/src/webparts/leadsSettings/components/LeadsSettings/LeadsSettings.tsx
Updates Leads to store configuration in application's personal folder
> Updates Leads to store configuration in application's personal folder

- solutions/PagesAPISolution/PowerShell/PagesController.ps1
| Bug fix?        | Yes
| New feature?    | No
| New sample?      | No
| Related issues?  | fixes #571 
Please describe the changes in this PR. Sample description or details around bugs which are being fixed.
*You can delete this section when you are submitting the pull request.* 
* *Please update this PR information accordingly. We'll use this as part of our release notes in monthly communications.*
* *Please target your PR to 'dev' branch.*
Thanks for your contribution! Sharing is caring.
> fix endpoint typo
